/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import classes.Employee;
import classes.EmployeeRecord;
import classes.LeaveManagement;
import classes.Payslip;
import classes.TimeAttendance;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import java.awt.Component;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Rosh
 */
public class FrmHRStaffHome extends javax.swing.JFrame {
    
    private Payslip payslip;
    private Employee employee;
    private TimeAttendance time;

    /**
     * Creates new form FrmAdminHome
     */
    public FrmHRStaffHome() {
        initComponents();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        JTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        btnUpdateEmployee = new javax.swing.JButton();
        btnAddStudent = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        txtSearch2 = new javax.swing.JTextField();
        lblTitle4 = new javax.swing.JLabel();
        btnEnter2 = new javax.swing.JButton();
        cbSelectDate = new javax.swing.JComboBox<>();
        lblTitle6 = new javax.swing.JLabel();
        btnARefresh = new javax.swing.JButton();
        btnAUpdate = new javax.swing.JButton();
        btnADelete = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        txtSearch3 = new javax.swing.JTextField();
        lblTitle5 = new javax.swing.JLabel();
        btnEnter3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblCredit = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblLeave = new javax.swing.JTable();
        btnRRefresh = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        txtSearch4 = new javax.swing.JTextField();
        lblTitle3 = new javax.swing.JLabel();
        btnEnter4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                loadEmployee(evt);
                loadLeave(evt);
                loadCredits(evt);
                loadAttendance(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 245, 239));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(48, 36, 58));
        jLabel1.setText("Welcome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 36, 58));
        jLabel3.setText("Manuel,");

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 179));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anna\\OneDrive\\Documents\\NetBeansProjects\\MotorPHPayrollSystem\\src\\main\\java\\icons\\MotorPHLogo.png")); // NOI18N

        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(48, 36, 58));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anna\\Downloads\\icons8-logout-30.png")); // NOI18N
        lblLogout.setText("Log out");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 179));

        jPanel6.setBackground(new java.awt.Color(255, 245, 239));

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmployee);
        if (tblEmployee.getColumnModel().getColumnCount() > 0) {
            tblEmployee.getColumnModel().getColumn(0).setResizable(false);
            tblEmployee.getColumnModel().getColumn(1).setResizable(false);
            tblEmployee.getColumnModel().getColumn(2).setResizable(false);
            tblEmployee.getColumnModel().getColumn(3).setResizable(false);
            tblEmployee.getColumnModel().getColumn(4).setResizable(false);
            tblEmployee.getColumnModel().getColumn(5).setResizable(false);
            tblEmployee.getColumnModel().getColumn(6).setResizable(false);
        }

        txtSearch.setToolTipText("");
        txtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 142, 76), 1, true));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblTitle.setText("Enter EmployeeID");

        btnEnter.setBackground(new java.awt.Color(254, 142, 76));
        btnEnter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("Search");
        btnEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterSearch(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(254, 142, 76));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshRecord(evt);
            }
        });

        btnDeleteEmployee.setBackground(new java.awt.Color(254, 142, 76));
        btnDeleteEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteEmployee.setText("DELETE");
        btnDeleteEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteRecord(evt);
            }
        });

        btnUpdateEmployee.setBackground(new java.awt.Color(254, 142, 76));
        btnUpdateEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateEmployee.setText("UPDATE");
        btnUpdateEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateRecord(evt);
            }
        });

        btnAddStudent.setBackground(new java.awt.Color(254, 142, 76));
        btnAddStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudent.setText("ADD");
        btnAddStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRecord(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnUpdateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter))
                .addGap(0, 0, 0)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnDeleteEmployee)
                    .addComponent(btnUpdateEmployee)
                    .addComponent(btnAddStudent))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTabbedPane.addTab("Employee", jPanel2);

        jPanel10.setBackground(new java.awt.Color(255, 204, 179));

        jPanel22.setBackground(new java.awt.Color(255, 245, 239));

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblAttendance);
        if (tblAttendance.getColumnModel().getColumnCount() > 0) {
            tblAttendance.getColumnModel().getColumn(0).setResizable(false);
            tblAttendance.getColumnModel().getColumn(1).setResizable(false);
            tblAttendance.getColumnModel().getColumn(2).setResizable(false);
            tblAttendance.getColumnModel().getColumn(3).setResizable(false);
            tblAttendance.getColumnModel().getColumn(4).setResizable(false);
            tblAttendance.getColumnModel().getColumn(5).setResizable(false);
            tblAttendance.getColumnModel().getColumn(6).setResizable(false);
        }

        txtSearch2.setToolTipText("");
        txtSearch2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 142, 76), 1, true));

        lblTitle4.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblTitle4.setText("Enter EmployeeID");

        btnEnter2.setBackground(new java.awt.Color(254, 142, 76));
        btnEnter2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnter2.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter2.setText("Search");
        btnEnter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));

        cbSelectDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "September", "October", "November", "December" }));

        lblTitle6.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblTitle6.setText("Show data for:");

        btnARefresh.setBackground(new java.awt.Color(254, 142, 76));
        btnARefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnARefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnARefresh.setText("Refresh");
        btnARefresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));

        btnAUpdate.setBackground(new java.awt.Color(254, 142, 76));
        btnAUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnAUpdate.setText("Update");
        btnAUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));

        btnADelete.setBackground(new java.awt.Color(254, 142, 76));
        btnADelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnADelete.setForeground(new java.awt.Color(255, 255, 255));
        btnADelete.setText("Delete");
        btnADelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSelectDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle6))
                .addGap(28, 28, 28)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(lblTitle4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnter2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnARefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnADelete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter2)
                    .addComponent(cbSelectDate, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnARefresh)
                    .addComponent(btnAUpdate)
                    .addComponent(btnADelete))
                .addGap(2, 2, 2)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle4)
                    .addComponent(lblTitle6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        JTabbedPane.addTab("Attendance", jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 204, 179));

        jPanel23.setBackground(new java.awt.Color(255, 245, 239));

        txtSearch3.setToolTipText("");
        txtSearch3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 142, 76), 1, true));

        lblTitle5.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblTitle5.setText("Enter EmployeeID");

        btnEnter3.setBackground(new java.awt.Color(254, 142, 76));
        btnEnter3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnter3.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter3.setText("Search");
        btnEnter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));
        btnEnter3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterSearch3(evt);
            }
        });

        tblCredit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblCredit);
        if (tblCredit.getColumnModel().getColumnCount() > 0) {
            tblCredit.getColumnModel().getColumn(0).setResizable(false);
            tblCredit.getColumnModel().getColumn(1).setResizable(false);
            tblCredit.getColumnModel().getColumn(2).setResizable(false);
            tblCredit.getColumnModel().getColumn(3).setResizable(false);
            tblCredit.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle5)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(txtSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnter3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter3))
                .addGap(7, 7, 7)
                .addComponent(lblTitle5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 245, 239));

        btnApprove.setBackground(new java.awt.Color(254, 142, 76));
        btnApprove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("Approve");
        btnApprove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                approveRequest(evt);
            }
        });

        btnReject.setBackground(new java.awt.Color(254, 142, 76));
        btnReject.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReject.setForeground(new java.awt.Color(255, 255, 255));
        btnReject.setText("Reject");
        btnReject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rejectRequest(evt);
            }
        });

        tblLeave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblLeave);
        if (tblLeave.getColumnModel().getColumnCount() > 0) {
            tblLeave.getColumnModel().getColumn(0).setResizable(false);
            tblLeave.getColumnModel().getColumn(1).setResizable(false);
            tblLeave.getColumnModel().getColumn(2).setResizable(false);
            tblLeave.getColumnModel().getColumn(3).setResizable(false);
            tblLeave.getColumnModel().getColumn(4).setResizable(false);
            tblLeave.getColumnModel().getColumn(5).setResizable(false);
            tblLeave.getColumnModel().getColumn(6).setResizable(false);
        }

        btnRRefresh.setBackground(new java.awt.Color(254, 142, 76));
        btnRRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRRefresh.setText("Refresh");
        btnRRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshRequest(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnRRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTabbedPane.addTab("Leave", jPanel11);

        jPanel16.setBackground(new java.awt.Color(255, 204, 179));

        jPanel19.setBackground(new java.awt.Color(255, 245, 239));

        txtSearch4.setToolTipText("");
        txtSearch4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 142, 76), 1, true));

        lblTitle3.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblTitle3.setText("Enter EmployeeID");

        btnEnter4.setBackground(new java.awt.Color(254, 142, 76));
        btnEnter4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnter4.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter4.setText("Search");
        btnEnter4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap(534, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle3)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(txtSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnter4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter4))
                .addGap(0, 0, 0)
                .addComponent(lblTitle3)
                .addContainerGap(472, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        JTabbedPane.addTab("Report", jPanel16);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTabbedPane)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadEmployee(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadEmployee
        String csvFilename = "C:\\Users\\Anna\\Downloads\\employeeDetails.csv";
        EmployeeRecord record = new EmployeeRecord();
        try {
            tblEmployee.setModel(record.fetchEmployees(csvFilename));
            adjustColumns(tblEmployee);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadEmployee

    private void Logout(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout
        this.dispose(); // Close the current window
        // Open or show the login frame
        FrmLogin loginFrame = new FrmLogin();
        loginFrame.setVisible(true);
        loginFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_Logout

    private void enterSearch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterSearch
        String searchQuery = txtSearch.getText();
        
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0); 

        try {
            String CSVFilename = "C:\\Users\\Anna\\Downloads\\employeeDetails.csv";
            boolean recordFound = false;
            
            try (CSVReader reader = new CSVReader(new FileReader(CSVFilename))) {
                String[] record;
                recordFound = false;
                while ((record = reader.readNext()) != null) {
                    for (String field : record) {
                        if (field.equalsIgnoreCase(searchQuery)) {
                            model.addRow(record);
                            recordFound = true;
                            break;
                        }
                    }
                }
            }

            if (!recordFound) {
                JOptionPane.showMessageDialog(this, "No matching record found", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            }
            
            adjustColumns(tblEmployee);
        }  catch (IOException | CsvValidationException ex) {
            JOptionPane.showMessageDialog(this, "Error reading CSV file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enterSearch

    private void refreshRecord(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshRecord
        String csvFilename = "C:\\Users\\Anna\\Downloads\\employeeDetails.csv";
        try {
            EmployeeRecord record = new EmployeeRecord();
            tblEmployee.setModel(record.fetchEmployees(csvFilename));
            
            txtSearch.setText("");
            
            adjustColumns(tblEmployee);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshRecord

    private void deleteRecord(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteRecord
        EmployeeRecord record = new EmployeeRecord();
        
        if (tblEmployee.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please choose an employee from the table first.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        String empID = tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(),0).toString();
        int employeeID = Integer.parseInt(empID);
        record.setEmployeeID(employeeID);
        record.setLastName(tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(), 1).toString());
        record.setFirstName(tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(), 2).toString());
        record.setBirthday(tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(), 3).toString());
        record.setAddress(tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(), 4).toString());

        String csvFilename = "C:\\Users\\Anna\\Downloads\\employeeDetails.csv";
        try {
            try (CSVReader reader = new CSVReader(new FileReader(csvFilename))) {
                String[] line;
                
                while((line=reader.readNext())!=null){
                    if(line[0].equals(empID)){
                        record.setBirthday(line[3]);
                        record.setAddress(line[4]);
                        record.setPhoneNumber(line[5]);
                        record.setStatus(line[10]);
                        record.setPosition(line[11]);
                        record.setImmediateSupervisor(line[12]);
                        break;
                    }
                }
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }

        FrmDeleteEmployee delete = new FrmDeleteEmployee(record);
        delete.setLocationRelativeTo(null);
        delete.setVisible(true);

        try {
            tblEmployee.setModel(record.fetchEmployees(csvFilename));
            adjustColumns(tblEmployee);
        } catch(IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.INFO, "An unexpected error occured.", ex);
        }
    }//GEN-LAST:event_deleteRecord

    private void updateRecord(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateRecord
        EmployeeRecord record = new EmployeeRecord();
        
        if (tblEmployee.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please choose an employee from the table first.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        String empID = tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(),0).toString();
        int employeeID = Integer.parseInt(empID);
        record.setEmployeeID(employeeID);
        record.setLastName(tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(), 1).toString());
        record.setFirstName(tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(), 2).toString());
        record.setBirthday(tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(), 3).toString());
        record.setAddress(tblEmployee.getModel().getValueAt(tblEmployee.getSelectedRow(), 4).toString());

        String csvFilename = "C:\\Users\\Anna\\Downloads\\employeeDetails.csv";
        try {
            try (CSVReader reader = new CSVReader(new FileReader(csvFilename))) {
                String[] line;
                
                while((line=reader.readNext())!=null){
                    if(line[0].equals(empID)){
                        record.setBirthday(line[3]);
                        record.setAddress(line[4]);
                        record.setPhoneNumber(line[5]);
                        record.setStatus(line[10]);
                        record.setPosition(line[11]);
                        record.setImmediateSupervisor(line[12]);
                        break;
                    }
                }
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }

        FrmUpdateEmployee update = new FrmUpdateEmployee(record);
        update.pack();
        update.setLocationRelativeTo(null);
        update.setVisible(true);

        try {
            tblEmployee.setModel(record.fetchEmployees(csvFilename));
            adjustColumns(tblEmployee);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateRecord

    private void addRecord(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRecord
        FrmAddEmployee add = new FrmAddEmployee();
        add.pack();
        add.setLocationRelativeTo(null);
        add.setVisible(true);
        
        String csvFilename = "C:\\Users\\Anna\\Downloads\\employeeDetails.csv";
        EmployeeRecord record = new EmployeeRecord();
        try {
            tblEmployee.setModel(record.fetchEmployees(csvFilename));
            adjustColumns(tblEmployee);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addRecord

    private void loadLeave(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadLeave
        String csvFilename = "leaveApplication.csv";
        EmployeeRecord record = new EmployeeRecord();
        try {
            tblLeave.setModel(record.fetchLeave(csvFilename));
            adjustColumns(tblLeave);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadLeave

    private void loadCredits(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadCredits
        String csvFilename = "C:\\Users\\Anna\\Downloads\\leaveRecord.csv";
        EmployeeRecord record = new EmployeeRecord();
        try {
            tblCredit.setModel(record.fetchCredit(csvFilename));
            adjustColumns(tblCredit);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadCredits

    private void approveRequest(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approveRequest
        LeaveManagement leave = new LeaveManagement();
        String csvFilename = "leaveApplication.csv";
        
        if (tblLeave.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please choose a request from the table first.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        String empID = tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(),1).toString();
        int employeeID = Integer.parseInt(empID);
        leave.setEmployeeID(employeeID);
        leave.setRequestDate(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 0).toString());
        leave.setLastName(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 2).toString());
        leave.setFirstName(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 3).toString());
        leave.setLeaveType(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 4).toString());
        leave.setDays(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 5).toString());
        leave.setStartDate(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 6).toString());
        leave.setEndDate(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 7).toString());
        leave.setStatus(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 8).toString());

        try {
            try (CSVReader reader = new CSVReader(new FileReader(csvFilename))) {
                String[] line;
                
                while((line=reader.readNext())!=null){
                    if(line[1].equals(empID)){
                        leave.setRequestDate(line[0]);
                        leave.setLastName(line[2]);
                        leave.setFirstName(line[3]);
                        leave.setLeaveType(line[4]);
                        leave.setDays(line[5]);
                        leave.setStartDate(line[6]);
                        leave.setEndDate(line[7]);
                        break;
                    }
                }
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }

        EmployeeRecord record = new EmployeeRecord();
        FrmApprove approve = new FrmApprove(leave);
        approve.pack();
        approve.setLocationRelativeTo(null);
        approve.setVisible(true);

        try {
            tblLeave.setModel(record.fetchLeave(csvFilename));
            adjustColumns(tblLeave);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_approveRequest

    private void rejectRequest(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rejectRequest
        LeaveManagement leave = new LeaveManagement();
        String csvFilename = "leaveApplication.csv";
        
        if (tblLeave.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please choose a request from the table first.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        String empID = tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(),1).toString();
        int employeeID = Integer.parseInt(empID);
        leave.setEmployeeID(employeeID);
        leave.setRequestDate(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 0).toString());
        leave.setLastName(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 2).toString());
        leave.setFirstName(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 3).toString());
        leave.setLeaveType(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 4).toString());
        leave.setDays(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 5).toString());
        leave.setStartDate(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 6).toString());
        leave.setEndDate(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 7).toString());
        leave.setStatus(tblLeave.getModel().getValueAt(tblLeave.getSelectedRow(), 8).toString());

        try {
            try (CSVReader reader = new CSVReader(new FileReader(csvFilename))) {
                String[] line;
                
                while((line=reader.readNext())!=null){
                    if(line[1].equals(empID)){
                        leave.setRequestDate(line[0]);
                        leave.setLastName(line[2]);
                        leave.setFirstName(line[3]);
                        leave.setLeaveType(line[4]);
                        leave.setDays(line[5]);
                        leave.setStartDate(line[6]);
                        leave.setEndDate(line[7]);
                        break;
                    }
                }
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }

        EmployeeRecord record = new EmployeeRecord();
        FrmReject reject = new FrmReject(leave);
        reject.pack();
        reject.setLocationRelativeTo(null);
        reject.setVisible(true);

        try {
            tblLeave.setModel(record.fetchLeave(csvFilename));
            adjustColumns(tblLeave);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rejectRequest

    private void enterSearch3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterSearch3
        String searchQuery = txtSearch3.getText();
        
        DefaultTableModel credit = (DefaultTableModel) tblCredit.getModel();
        DefaultTableModel request = (DefaultTableModel) tblLeave.getModel();
        credit.setRowCount(0); 
        request.setRowCount(0);

        try {
            String creditCSVFilename = "C:\\Users\\Anna\\Downloads\\leaveRecord.csv";
            String requestCSVFilename = "leaveApplication.csv";
            boolean recordFound = false;
            
            try (CSVReader reader = new CSVReader(new FileReader(creditCSVFilename))) {
                String[] record;
                recordFound = false;
                while ((record = reader.readNext()) != null) {
                    for (String field : record) {
                        if (field.equalsIgnoreCase(searchQuery)) {
                            credit.addRow(record);
                            recordFound = true;
                            break;
                        }
                    }
                }
            }
            
            try (CSVReader reader = new CSVReader(new FileReader(requestCSVFilename))) {
                String[] record;
                while ((record = reader.readNext()) != null) {
                    for (String field : record) {
                        if (field.equalsIgnoreCase(searchQuery)) {
                            request.addRow(record);
                            recordFound = true;
                            break;
                        }
                    }
                }
            }
            
            if (!recordFound) {
                JOptionPane.showMessageDialog(this, "No matching record found", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            }
            
            adjustColumns(tblCredit);
        }  catch (IOException | CsvValidationException ex) {
            JOptionPane.showMessageDialog(this, "Error reading CSV file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enterSearch3

    private void refreshRequest(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshRequest
        String creditCSVFilename = "C:\\Users\\Anna\\Downloads\\leaveRecord.csv";
        String requestCSVFilename = "leaveApplication.csv";
        try {
            EmployeeRecord record = new EmployeeRecord();
            tblCredit.setModel(record.fetchCredit(creditCSVFilename));
            tblLeave.setModel(record.fetchLeave(requestCSVFilename));
            
            txtSearch3.setText("");
            
            adjustColumns(tblCredit);
            adjustColumns(tblLeave);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshRequest

    private void loadAttendance(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadAttendance
        String csvFilename = "attendanceRecord.csv";
        EmployeeRecord record = new EmployeeRecord();
        try {
            tblAttendance.setModel(record.fetchAttendance(csvFilename));
            adjustColumns(tblAttendance);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadAttendance

    // Display current time and date
    public void setTime() {
        Thread updateTimeThread = new Thread(() -> {
            while (true) {
                // Get current time
                Date date = new Date();
                SimpleDateFormat stf = new SimpleDateFormat("h:mm:ss aa");
                SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd-MM-yyyy");
                String realTime = stf.format(date);
                
                // Update time label
                SwingUtilities.invokeLater(() -> lblTime.setText(realTime));
                lblDate.setText(sdf.format(date));
            }
        });
        updateTimeThread.start();
    }
    
    private void adjustColumns(JTable table) {
        TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int maxWidth = 0;
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer cellRenderer = table.getCellRenderer(row, column);
                Object value = table.getValueAt(row, column);
                Component comp = cellRenderer.getTableCellRendererComponent(table, value, false, false, row, column);
                maxWidth = Math.max(comp.getPreferredSize().width, maxWidth);
                table.getColumnModel().getColumn(column).setCellRenderer(centerRenderer);
            }
            TableColumn col = columnModel.getColumn(column);
            col.setPreferredWidth(maxWidth);
        }
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHRStaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHRStaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHRStaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHRStaffHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHRStaffHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JButton btnADelete;
    private javax.swing.JButton btnARefresh;
    private javax.swing.JButton btnAUpdate;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnEnter2;
    private javax.swing.JButton btnEnter3;
    private javax.swing.JButton btnEnter4;
    private javax.swing.JButton btnRRefresh;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnUpdateEmployee;
    private javax.swing.JComboBox<String> cbSelectDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JTable tblAttendance;
    private javax.swing.JTable tblCredit;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblLeave;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch2;
    private javax.swing.JTextField txtSearch3;
    private javax.swing.JTextField txtSearch4;
    // End of variables declaration//GEN-END:variables
}
