/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import classes.Employee;
import classes.EmployeeRecord;
import classes.Payslip;
import classes.TimeAttendance;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import java.awt.Component;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Rosh
 */
public class FrmPayrollStaff extends javax.swing.JFrame {
    

    /**
     * Creates new form FrmPayrollStaff
     */
    public FrmPayrollStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        JTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPayroll = new javax.swing.JTable();
        txtPSearch = new javax.swing.JTextField();
        lblTitle2 = new javax.swing.JLabel();
        btnPEnter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        cbStartDate = new javax.swing.JComboBox<>();
        jLabel65 = new javax.swing.JLabel();
        cbEndDate = new javax.swing.JComboBox<>();
        jLabel66 = new javax.swing.JLabel();
        cbEmployee = new javax.swing.JComboBox<>();
        lblPFirstName = new javax.swing.JLabel();
        txtPFirstName = new javax.swing.JTextField();
        txtPLastName = new javax.swing.JTextField();
        lblPLastName = new javax.swing.JLabel();
        lblPBasicSalary = new javax.swing.JLabel();
        txtPBasicSalary = new javax.swing.JTextField();
        txtPRiceSubsidy = new javax.swing.JTextField();
        lblPRiceSubsidy = new javax.swing.JLabel();
        lblPPhoneAllowance = new javax.swing.JLabel();
        txtPPhoneAllowance = new javax.swing.JTextField();
        lblPSemiMonthly = new javax.swing.JLabel();
        txtPDaysWorked = new javax.swing.JTextField();
        lblPHourlyRate = new javax.swing.JLabel();
        txtPOvertime = new javax.swing.JTextField();
        btnPGenerate = new javax.swing.JButton();
        btnPUpdate = new javax.swing.JButton();
        btnPRefresh = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        txtSearch3 = new javax.swing.JTextField();
        lblTitle3 = new javax.swing.JLabel();
        btnEnter3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                loadEmployee(evt);
                loadPayroll(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1013, 633));

        jPanel5.setBackground(new java.awt.Color(255, 245, 239));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(48, 36, 58));
        jLabel1.setText("Welcome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 36, 58));
        jLabel3.setText("Manuel,");

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 179));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anna\\OneDrive\\Documents\\NetBeansProjects\\MotorPHPayrollSystem\\src\\main\\java\\icons\\MotorPHLogo.png")); // NOI18N

        lblLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(48, 36, 58));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anna\\Downloads\\icons8-logout-30.png")); // NOI18N
        lblLogout.setText("Log out");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutLogout(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 179));

        jPanel6.setBackground(new java.awt.Color(255, 245, 239));

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        txtSearch.setToolTipText("");
        txtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 142, 76), 1, true));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblTitle.setText("Enter EmployeeID");

        btnEnter.setBackground(new java.awt.Color(254, 142, 76));
        btnEnter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("Search");
        btnEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterSearch(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(254, 142, 76));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshRecord(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter))
                .addGap(0, 0, 0)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRefresh)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTabbedPane.addTab("Employee", jPanel2);

        jPanel12.setBackground(new java.awt.Color(255, 204, 179));

        jPanel15.setBackground(new java.awt.Color(255, 245, 239));

        tblPayroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPayroll);
        if (tblPayroll.getColumnModel().getColumnCount() > 0) {
            tblPayroll.getColumnModel().getColumn(0).setResizable(false);
            tblPayroll.getColumnModel().getColumn(1).setResizable(false);
            tblPayroll.getColumnModel().getColumn(2).setResizable(false);
            tblPayroll.getColumnModel().getColumn(3).setResizable(false);
        }

        txtPSearch.setToolTipText("");
        txtPSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 142, 76), 1, true));

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblTitle2.setText("Enter EmployeeID");

        btnPEnter.setBackground(new java.awt.Color(254, 142, 76));
        btnPEnter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnPEnter.setText("Enter");
        btnPEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));
        btnPEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEnterSearch(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(lblTitle2)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(txtPSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addComponent(btnPEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPEnter))
                .addGap(0, 0, 0)
                .addComponent(lblTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 245, 239));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Process Payroll");

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel61.setText("Start Date:");

        cbStartDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "09/01/2022", "10/01/2022", "11/01/2022", "12/01/2022" }));
        cbStartDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel65.setText("End Date:");

        cbEndDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "09/30/2022", "10/31/2022", "11/30/2022", "12/31/2022" }));
        cbEndDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setText("Select Employee:");

        cbEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "All", "10001", "10002", "10003", "10004", "10005", "10006", "10007", "10008", "10009", "10010", "10011", "10012", "10013", "10014", "10015", "10016", "10017", "10018", "10019", "10020", "10021", "10022", "10023", "10024", "10025", "10026", "10027", "10028", "10029", "10030", "10031", "10032", "10033", "10034" }));
        cbEmployee.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectEmployee(evt);
            }
        });

        lblPFirstName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPFirstName.setText("First Name");

        txtPFirstName.setEditable(false);
        txtPFirstName.setBackground(new java.awt.Color(255, 245, 239));
        txtPFirstName.setText("-");
        txtPFirstName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtPLastName.setEditable(false);
        txtPLastName.setBackground(new java.awt.Color(255, 245, 239));
        txtPLastName.setText("-");
        txtPLastName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblPLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPLastName.setText("Last Name");

        lblPBasicSalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPBasicSalary.setText("Basic Salary");

        txtPBasicSalary.setEditable(false);
        txtPBasicSalary.setBackground(new java.awt.Color(255, 245, 239));
        txtPBasicSalary.setText("-");
        txtPBasicSalary.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtPRiceSubsidy.setEditable(false);
        txtPRiceSubsidy.setBackground(new java.awt.Color(255, 245, 239));
        txtPRiceSubsidy.setText("-");
        txtPRiceSubsidy.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblPRiceSubsidy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPRiceSubsidy.setText("Rice Subsidy");

        lblPPhoneAllowance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPPhoneAllowance.setText("Phone Allowance");

        txtPPhoneAllowance.setEditable(false);
        txtPPhoneAllowance.setBackground(new java.awt.Color(255, 245, 239));
        txtPPhoneAllowance.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPPhoneAllowance.setText("-");
        txtPPhoneAllowance.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPPhoneAllowance.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPSemiMonthly.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPSemiMonthly.setText("Days Worked");

        txtPDaysWorked.setEditable(false);
        txtPDaysWorked.setBackground(new java.awt.Color(255, 245, 239));
        txtPDaysWorked.setText("-");
        txtPDaysWorked.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblPHourlyRate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPHourlyRate.setText("Overtime");

        txtPOvertime.setEditable(false);
        txtPOvertime.setBackground(new java.awt.Color(255, 245, 239));
        txtPOvertime.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPOvertime.setText("-");
        txtPOvertime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPOvertime.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnPGenerate.setBackground(new java.awt.Color(254, 142, 76));
        btnPGenerate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPGenerate.setForeground(new java.awt.Color(255, 255, 255));
        btnPGenerate.setText("GENERATE SALARY");
        btnPGenerate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateSalary(evt);
            }
        });

        btnPUpdate.setBackground(new java.awt.Color(254, 142, 76));
        btnPUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnPUpdate.setText("UPDATE");
        btnPUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatePayroll(evt);
            }
        });

        btnPRefresh.setBackground(new java.awt.Color(254, 142, 76));
        btnPRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnPRefresh.setText("REFRESH");
        btnPRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pRefresh(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(343, 343, 343))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtPFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbEmployee, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtPLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(lblPBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(150, 150, 150)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPSemiMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(331, 331, 331)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPDaysWorked, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPGenerate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPRefresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(cbStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65)
                    .addComponent(cbEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel66)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPFirstName)
                            .addComponent(lblPPhoneAllowance))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPLastName)
                            .addComponent(lblPSemiMonthly))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPBasicSalary)
                            .addComponent(lblPHourlyRate)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPRiceSubsidy))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(btnPGenerate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPUpdate)
                            .addGap(12, 12, 12)
                            .addComponent(btnPRefresh))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(txtPRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPDaysWorked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 839, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        JTabbedPane.addTab("Payroll", jPanel12);

        jPanel16.setBackground(new java.awt.Color(255, 204, 179));

        jPanel17.setBackground(new java.awt.Color(255, 245, 239));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jPanel19.setBackground(new java.awt.Color(255, 245, 239));

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblReport);

        txtSearch3.setToolTipText("");
        txtSearch3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 142, 76), 1, true));

        lblTitle3.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        lblTitle3.setText("Enter EmployeeID");

        btnEnter3.setBackground(new java.awt.Color(254, 142, 76));
        btnEnter3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnter3.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter3.setText("Search");
        btnEnter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 142, 76), 0));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGap(0, 197, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle3)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(txtSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnter3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter3))
                .addGap(0, 0, 0)
                .addComponent(lblTitle3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        JTabbedPane.addTab("Report", jPanel16);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTabbedPane)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutLogout(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutLogout
        this.dispose(); // Close the current window
        // Open or show the login frame
        FrmLogin loginFrame = new FrmLogin();
        loginFrame.setVisible(true);
        loginFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_lblLogoutLogout

    private void pEnterSearch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEnterSearch
        String searchQuery = txtPSearch.getText();

        DefaultTableModel model = (DefaultTableModel) tblPayroll.getModel();
        model.setRowCount(0);

        try {
            String CSVFilename = "payrollPayslip.csv";
            boolean recordFound = false;

            try (CSVReader reader = new CSVReader(new FileReader(CSVFilename))) {
                String[] record;
                recordFound = false;
                while ((record = reader.readNext()) != null) {
                    for (String field : record) {
                        if (field.equalsIgnoreCase(searchQuery)) {
                            model.addRow(record);
                            recordFound = true;
                            break;
                        }
                    }
                }
            }

            if (!recordFound) {
                JOptionPane.showMessageDialog(this, "No matching record found", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            }

            adjustColumns(tblPayroll);
        }  catch (IOException | CsvValidationException ex) {
            JOptionPane.showMessageDialog(this, "Error reading CSV file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pEnterSearch

    private void generateSalary(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateSalary
        TimeAttendance time = new TimeAttendance();
        Employee employee = new Employee();
        Payslip payslip = new Payslip();
        
        String start = String.valueOf(cbStartDate.getSelectedItem());
        String end = String.valueOf(cbEndDate.getSelectedItem());
        String employeeID = String.valueOf(cbEmployee.getSelectedItem());
        double overTime = Double.parseDouble(txtPOvertime.getText());
        float daysWorked = Float.parseFloat(txtPDaysWorked.getText());

        if (start.equals("-") || end.equals("-")) {
            JOptionPane.showMessageDialog(null, "Please select valid start and end dates.", "Invalid Dates", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Calculate total benefits
            double riceSubsidy = Double.parseDouble(txtPRiceSubsidy.getText());
            double phoneAllowance = Double.parseDouble(txtPPhoneAllowance.getText());
            double totalBenefits = payslip.calculateTotalBenefits(riceSubsidy, phoneAllowance);
            

            // Calculate deductions
            double monthlyRate = Double.parseDouble(txtPBasicSalary.getText());
            double sss = Double.parseDouble(payslip.calculateSSS(monthlyRate));
            double philhealth = Double.parseDouble(payslip.calculatePhilhealth(monthlyRate));
            double pagibig = Double.parseDouble(payslip.calculatePagibig(monthlyRate));
            double tax = Double.parseDouble(payslip.calculateTax(monthlyRate));
            double totalDeductions = payslip.calculateTotalDeductions(sss, philhealth, pagibig, tax);

            // Calculate gross income
            double grossIncome = payslip.calculateGrossIncome(monthlyRate, overTime, totalDeductions);
            
            // Calculate daily rate
            double dailyRate = payslip.calculateDailyRate(monthlyRate, daysWorked);

            // Calculate TakeHome Pay
            double takeHomePay = payslip.calculateTakeHomePay(grossIncome, totalDeductions);

            // Create payroll file
            EmployeeRecord record = new EmployeeRecord();
            record.createPayrollFile("payrollPayslip.csv" , start, end, employeeID, monthlyRate, dailyRate, daysWorked, overTime, grossIncome, riceSubsidy, phoneAllowance, totalBenefits, sss, philhealth, pagibig, tax, totalDeductions, takeHomePay);
            
            // Update payroll table
            String csvFilename = "payrollPayslip.csv";
            tblPayroll.setModel(record.fetchPayslipReport(csvFilename));
            adjustColumns(tblPayroll);

        } catch (IOException | CsvValidationException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error generating payroll. Please ensure all input data is valid.", "Payroll Generation Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateSalary

    private void pRefresh(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRefresh
        // Reset text fields
        txtPSearch.setText(" ");
        cbStartDate.setSelectedIndex(0);
        cbEndDate.setSelectedIndex(0);
        cbEmployee.setSelectedIndex(0);
        txtPLastName.setText("-");
        txtPFirstName.setText("-");
        txtPBasicSalary.setText("-");
        txtPRiceSubsidy.setText("-");
        txtPPhoneAllowance.setText("-");
        txtPDaysWorked.setText("-");
        txtPOvertime.setText("-");
    }//GEN-LAST:event_pRefresh

    private void updatePayroll(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePayroll
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePayroll

    private void enterSearch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterSearch
        String searchQuery = txtSearch.getText();

        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);

        try {
            String CSVFilename = "C:\\Users\\Anna\\Downloads\\employeeDetails.csv";
            boolean recordFound = false;

            try (CSVReader reader = new CSVReader(new FileReader(CSVFilename))) {
                String[] record;
                recordFound = false;
                while ((record = reader.readNext()) != null) {
                    for (String field : record) {
                        if (field.equalsIgnoreCase(searchQuery)) {
                            model.addRow(record);
                            recordFound = true;
                            break;
                        }
                    }
                }
            }

            if (!recordFound) {
                JOptionPane.showMessageDialog(this, "No matching record found", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            }

            adjustColumns(tblEmployee);
        }  catch (IOException | CsvValidationException ex) {
            JOptionPane.showMessageDialog(this, "Error reading CSV file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enterSearch

    private void refreshRecord(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshRecord
        String csvFilename = "C:\\Users\\Anna\\Downloads\\employeeDetails.csv";
        try {
            EmployeeRecord record = new EmployeeRecord();
            tblEmployee.setModel(record.fetchEmployees(csvFilename));

            txtSearch.setText("");

            adjustColumns(tblEmployee);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshRecord

    private void loadEmployee(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadEmployee
        String csvFilename = "employeeDetails.csv";
        EmployeeRecord record = new EmployeeRecord();
        try {
            tblEmployee.setModel(record.fetchPayroll(csvFilename));
            adjustColumns(tblEmployee);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadEmployee

    private void loadPayroll(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadPayroll
        String csvFilename = "payrollPayslip.csv";
        EmployeeRecord record = new EmployeeRecord();
        try {
            tblPayroll.setModel(record.fetchPayslipReport(csvFilename));
            adjustColumns(tblPayroll);
        } catch (IOException | CsvValidationException ex) {
            Logger.getLogger(FrmHRStaffHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadPayroll

    private void selectEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectEmployee
        if (cbStartDate.getSelectedIndex() == -1 || cbEndDate.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Please select start and end dates first.", "Missing Dates", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int empID =  Integer.parseInt((String) cbEmployee.getSelectedItem());
        String start = String.valueOf(cbStartDate.getSelectedItem());
        String end = String.valueOf(cbEndDate.getSelectedItem());
        
        try {
            TimeAttendance time = new TimeAttendance();
            Employee employee = new Employee();
            float daysWorked = time.calculateDays(start, end, empID, "attendanceRecord.csv");
            float overTime = time.calculateOvertime(start, end, employee, "attendanceRecord.csv");
            
            updateDaysWorked(daysWorked);
            updateOvertime(overTime);
            
            // Load employee details from CSV
            String CSVFilename = "C:\\Users\\Anna\\Downloads\\employeeDetails.csv";
            boolean recordFound;
            try (CSVReader reader = new CSVReader(new FileReader(CSVFilename))) {
                String[] record;
                recordFound = false;
                while ((record = reader.readNext()) != null) {
                    for (String field : record) {
                        if (record[0].equals(String.valueOf(empID))) {
                            txtPLastName.setText(record[1]);
                            txtPFirstName.setText(record[2]);
                            txtPBasicSalary.setText(record[13]);
                            txtPRiceSubsidy.setText(record[14]);
                            txtPPhoneAllowance.setText(record[15]);

                            recordFound = true;
                            break;
                        }
                    }
                }
            }

            if (!recordFound) {
                JOptionPane.showMessageDialog(this, "No matching record found", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            }
        }  catch (CsvValidationException | IOException | ParseException ex) {
            JOptionPane.showMessageDialog(this, "Error reading CSV file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_selectEmployee

    private void adjustColumns(JTable table) {
        TableColumnModel columnModel = table.getColumnModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        for (int column = 0; column < table.getColumnCount(); column++) {
            int maxWidth = 0;
            
            DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.CENTER);
            table.getColumnModel().getColumn(column).setCellRenderer(renderer);
            
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer cellRenderer = table.getCellRenderer(row, column);
                Object value = table.getValueAt(row, column);
                Component comp = cellRenderer.getTableCellRendererComponent(table, value, false, false, row, column);
                maxWidth = Math.max(comp.getPreferredSize().width, maxWidth);
            }
            
            TableColumn col = columnModel.getColumn(column);
            col.setPreferredWidth(maxWidth);
        }
    }  
    
    private void updateDaysWorked(float daysWorked) {
        if (daysWorked == 0) {
            txtPDaysWorked.setText("No attendance records.");
        } else {
            txtPDaysWorked.setText(String.format("%.0f", daysWorked));
        }
    }
    
    private void updateOvertime(float overTime) {
        DecimalFormat df = new DecimalFormat("#,###.##");
        txtPOvertime.setText(df.format(overTime));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPayrollStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPayrollStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPayrollStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPayrollStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPayrollStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnEnter3;
    private javax.swing.JButton btnPEnter;
    private javax.swing.JButton btnPGenerate;
    private javax.swing.JButton btnPRefresh;
    private javax.swing.JButton btnPUpdate;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cbEmployee;
    private javax.swing.JComboBox<String> cbEndDate;
    private javax.swing.JComboBox<String> cbStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblPBasicSalary;
    private javax.swing.JLabel lblPFirstName;
    private javax.swing.JLabel lblPHourlyRate;
    private javax.swing.JLabel lblPLastName;
    private javax.swing.JLabel lblPPhoneAllowance;
    private javax.swing.JLabel lblPRiceSubsidy;
    private javax.swing.JLabel lblPSemiMonthly;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTable tblPayroll;
    private javax.swing.JTable tblReport;
    private javax.swing.JTextField txtPBasicSalary;
    private javax.swing.JTextField txtPDaysWorked;
    private javax.swing.JTextField txtPFirstName;
    private javax.swing.JTextField txtPLastName;
    private javax.swing.JTextField txtPOvertime;
    private javax.swing.JTextField txtPPhoneAllowance;
    private javax.swing.JTextField txtPRiceSubsidy;
    private javax.swing.JTextField txtPSearch;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch3;
    // End of variables declaration//GEN-END:variables
}
